apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-qa
  namespace: qa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app-qa
  template:
    metadata:
      labels:
        app: django-app-qa
    spec:
      containers:
        - name: django-app-qa
          image: hz3866/django-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "True"
            - name: DJANGO_ALLOWED_HOSTS
              value: "*"