apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app-prod
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-app-prod
  template:
    metadata:
      labels:
        app: django-app-prod
    spec:
      containers:
        - name: django-app
          image: hz3866/django-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000